# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20161230_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.UserProfile'),
        ),
    ]
