# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20161230_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_time', models.DateTimeField(auto_now=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_is_followed', to='gestion.UserProfile')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_follows', to='gestion.UserProfile')),
            ],
        ),
    ]
